### PR TITLE
LAMMPS small build with OBMD easyconfig template with `software-commit`

### PR DESCRIPTION
**Pull request by laraPPr**

### CODE REVIEW

**Comment by laraPPr** [comment]
bot: build

**Comment by Neves-P** [comment]
It looks like it errored while translating the LAMMPS version on the easyblock. I'll check if it used the easyblock filewe're expecting (as given via the commit in the easystack)
```
== ... (took 11 secs)
ERROR: Traceback (most recent call last):
  File "/tmp/eb-riopifj7/eb-o7vwvy1c/included-easyblocks-7oztf6r9/easybuild/easyblocks/lammps.py", line 177, in translate_lammps_version
    return '.'.join([items[2], month_map[items[1].upper()], '%02d' % int(items[0])])
                               ~~~~~~~~~^^^^^^^^^^^^^^^^^^
KeyError: 'C'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen2/software/EasyBuild/4.9.4/lib/python3.11/site-packages/easybuild/main.py", line 137, in build_and_install_software
    (ec_res['success'], app_log, err) = build_and_install_one(ec, init_env)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen2/software/EasyBuild/4.9.4/lib/python3.11/site-packages/easybuild/framework/easyblock.py", line 4276, in build_and_install_one
    result = app.run_all_steps(run_test_cases=run_test_cases)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen2/software/EasyBuild/4.9.4/lib/python3.11/site-packages/easybuild/framework/easyblock.py", line 4155, in run_all_steps
    self.run_step(step_name, step_methods)
  File "/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen2/software/EasyBuild/4.9.4/lib/python3.11/site-packages/easybuild/framework/easyblock.py", line 3990, in run_step
    step_method(self)()
  File "/tmp/eb-riopifj7/eb-o7vwvy1c/included-easyblocks-7oztf6r9/easybuild/easyblocks/lammps.py", line 236, in prepare_step
    self.cur_version = translate_lammps_version(self.version, path=self.start_dir)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/eb-riopifj7/eb-o7vwvy1c/included-easyblocks-7oztf6r9/easybuild/easyblocks/lammps.py", line 188, in translate_lammps_version
    return '.'.join([items[2], month_map[items[1].upper()], '%02d' % int(items[0])])
                               ~~~~~~~~~^^^^^^^^^^^^^^^^^^
KeyError: ' '
```

**Comment by laraPPr** [comment]
Ah I think I know what the cause is

**Comment by laraPPr** [comment]
bot: build

**Comment by laraPPr** [comment]
@Neves-P will you deploy it or not yet?

**Pull request merged**
